# Generated by Django 5.1.7 on 2025-03-19 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('traveler_type', models.CharField(choices=[('luxury', 'Luxury'), ('medium', 'Medium'), ('budget', 'Budget')], default='medium', max_length=10)),
                ('savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('accommodation_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transportation_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('food_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('activities_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
