# Generated by Django 5.1.7 on 2025-03-22 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='accommodation_budget',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='activities_budget',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='food_budget',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='transportation_budget',
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('transport', 'Transport'), ('accommodation', 'Accommodation'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.trip')),
            ],
        ),
    ]
