# Generated by Django 5.1.7 on 2025-04-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_trip_accommodation_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(default='GBP', max_length=3),
        ),
    ]
