# Generated by Django 5.1.7 on 2025-04-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='budget_tolerance',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='trip',
            name='recommended_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
