# Generated by Django 5.1.7 on 2025-04-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trip_budget_tolerance_trip_recommended_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='budget_tolerance',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='recommended_budget',
        ),
    ]
